### ISSUE TITLE
[Clickhouse Output] WaitGroup is reused before previous Wait has returned

### ISSUE THREAD

**Issue by childe** [childe/gohangout#119]
>  [2021-01-13 11:35:43,642] {docker_operator.py:235} INFO - panic: sync: WaitGroup is reused before previous Wait has returned
[2021-01-13 11:35:43,643] {docker_operator.py:235} INFO - goroutine 4408 [running]:
[2021-01-13 11:35:43,643] {docker_operator.py:235} INFO - sync.(*WaitGroup).Wait(0xc0003fe1c8)
[2021-01-13 11:35:43,643] {docker_operator.py:235} INFO - /usr/lib/golang/src/sync/waitgroup.go:132 +0xae
[2021-01-13 11:35:43,643] {docker_operator.py:235} INFO - github.com/childe/gohangout/output.(*ClickhouseOutput).awaitclose.func2.1(0xc0003fe0f0, 0xc2aac7c0c0)
[2021-01-13 11:35:43,643] {docker_operator.py:235} INFO - /home/appuser/gohangout/output/clickhouse_output.go:460 +0x33
[2021-01-13 11:35:43,643] {docker_operator.py:235} INFO - created by github.com/childe/gohangout/output.(*ClickhouseOutput).awaitclose.func2
[2021-01-13 11:35:43,643] {docker_operator.py:235} INFO - /home/appuser/gohangout/output/clickhouse_output.go:458 +0x49

**Comment by childe** [comment]
http://ohmycat.me/2019/05/29/waitgroup-in-golang.html 因为有可能CloseAwait的时候, 还有新的 Bulk 在做, 导致  wg.Wait 之后还有 wg.Add
一时想不到彻底的解决方法.

**Comment by childe** [comment]
fix in #d8e43bd
