### ISSUE TITLE
最新hangout kafka 消费不定期panic ，重启后一段时间恢复后有panic

### ISSUE THREAD

**Issue by zcola** [childe/gohangout#252]
kafka 1.1.1 个别topic 这样，1.8.2 就有这个问题回退到logstash 一直正常，今天打了一个最新的1.10 hangout 还是有这个问题

```
I1011 17:45:51.257189       1 simple_consumer.go:163] "get leader" logger="healer" topic="welland_g117_logtail" partitionID=40 leaderID=2
I1011 17:45:51.258221       1 simple_consumer.go:225] "get commited offset" logger="healer" topic="welland_g117_logtail" partitionID=4
I1011 17:45:51.258254       1 simple_consumer.go:225] "get commited offset" logger="healer" topic="welland_g117_logtail" partitionID=56
I1011 17:45:51.258772       1 simple_consumer.go:225] "get commited offset" logger="healer" topic="welland_g117_logtail" partitionID=55
I1011 17:45:51.258793       1 simple_consumer.go:225] "get commited offset" logger="healer" topic="welland_g117_logtail" partitionID=21
I1011 17:45:51.257217       1 simple_consumer.go:176] "leader broker created" logger="healer" leaderID=17 leaderAddress="canal-kafka17-welland.dsdsad:9092" topic="welland_g117_logtail" partitionID=19
I1011 17:45:51.258809       1 simple_consumer.go:225] "get commited offset" logger="healer" topic="welland_g117_logtail" partitionID=19
I1011 17:45:51.261460       1 simple_consumer.go:176] "leader broker created" logger="healer" leaderID=7 leaderAddress="canal-kafka07-welland.dsdsad:9092" topic="welland_g117_logtail" partitionID=45
I1011 17:45:51.261815       1 simple_consumer.go:225] "get commited offset" logger="healer" topic="welland_g117_logtail" partitionID=45
I1011 17:45:51.351033       1 simple_consumer.go:225] "get commited offset" logger="healer" topic="welland_g117_logtail" partitionID=68
I1011 17:45:51.351417       1 simple_consumer.go:176] "leader broker created" logger="healer" leaderID=32 leaderAddress="canal-kafka32-welland.dsdsad:9092" topic="welland_g117_logtail" partitionID=70
I1011 17:45:51.351441       1 simple_consumer.go:225] "get commited offset" logger="healer" topic="welland_g117_logtail" partitionID=70
I1011 17:45:51.351633       1 simple_consumer.go:176] "leader broker created" logger="healer" leaderID=15 leaderAddress="canal-kafka15-welland.dsdsad:9092" topic="welland_g117_logtail" partitionID=17
I1011 17:45:51.351656       1 simple_consumer.go:225] "get commited offset" logger="healer" topic="welland_g117_logtail" partitionID=17
I1011 17:45:51.352908       1 simple_consumer.go:176] "leader broker created" logger="healer" leaderID=27 leaderAddress="canal-kafka27-welland.dsdsad:9092" topic="welland_g117_logtail" partitionID=65
I1011 17:45:51.352944       1 simple_consumer.go:225] "get commited offset" logger="healer" topic="welland_g117_logtail" partitionID=65
I1011 17:45:51.552141       1 simple_consumer.go:176] "leader broker created" logger="healer" leaderID=14 leaderAddress="canal-kafka14-welland.dsdsad:9092" topic="welland_g117_logtail" partitionID=16
I1011 17:45:51.553091       1 simple_consumer.go:225] "get commited offset" logger="healer" topic="welland_g117_logtail" partitionID=16
I1011 17:45:51.552245       1 simple_consumer.go:176] "leader broker created" logger="healer" leaderID=3 leaderAddress="canal-kafka03-welland.dsdsad:9092" topic="welland_g117_logtail" partitionID=41
I1011 17:45:51.553253       1 simple_consumer.go:225] "get commited offset" logger="healer" topic="welland_g117_logtail" partitionID=41
I1011 17:45:51.552276       1 simple_consumer.go:176] "leader broker created" logger="healer" leaderID=33 leaderAddress="canal-kafka33-welland.dsdsad:9092" topic="welland_g117_logtail" partitionID=35
I1011 17:45:51.553339       1 simple_consumer.go:225] "get commited offset" logger="healer" topic="welland_g117_logtail" partitionID=35
I1011 17:45:51.653612       1 simple_consumer.go:176] "leader broker created" logger="healer" leaderID=21 leaderAddress="canal-kafka21-welland.dsdsad:9092" topic="welland_g117_logtail" partitionID=59
I1011 17:45:51.653832       1 simple_consumer.go:225] "get commited offset" logger="healer" topic="welland_g117_logtail" partitionID=59
I1011 17:45:51.655364       1 simple_consumer.go:176] "leader broker created" logger="healer" leaderID=18 leaderAddress="canal-kafka18-welland.dsdsad:9092" topic="welland_g117_logtail" partitionID=20
I1011 17:45:51.655402       1 simple_consumer.go:225] "get commited offset" logger="healer" topic="welland_g117_logtail" partitionID=20
I1011 17:45:51.751460       1 simple_consumer.go:176] "leader broker created" logger="healer" leaderID=2 leaderAddress="canal-kafka02-welland.dsdsad:9092" topic="welland_g117_logtail" partitionID=40
I1011 17:45:51.751519       1 simple_consumer.go:225] "get commited offset" logger="healer" topic="welland_g117_logtail" partitionID=40
panic: runtime error: slice bounds out of range [17:13]
goroutine 1699 [running]:
github.com/childe/healer.(*fetchResponseStreamDecoder).decodeMessageSetMagic0or1(0xc010df3e00, {0xc010d8d968, 0x14}, 0x3e, 0x12?, {0xc010d8d9b0, 0x11, 0x11})
#011/home/zcola/go/pkg/mod/github.com/childe/healer@v0.6.11/fetch_response.go:120 +0x63c
github.com/childe/healer.(*fetchResponseStreamDecoder).decodeMessageSet(0xc010df3e00, {0xc010d8d968, 0x14}, 0x3e, 0x2e4386, 0x6dd8?)
#011/home/zcola/go/pkg/mod/github.com/childe/healer@v0.6.11/fetch_response.go:303 +0x138
github.com/childe/healer.(*fetchResponseStreamDecoder).decodePartitionResponse(0xc010df3e00, {0xc010d8d968, 0x14},0x3e, 0x2e4386, 0x6dd8?)
#011/home/zcola/go/pkg/mod/github.com/childe/healer@v0.6.11/fetch_response.go:303 +0x138
github.com/childe/healer.(*fetchResponseStreamDecoder).decodePartitionResponse(0xc010df3e00, {0xc010d8d968, 0x14}, 0x0)
#011/home/zcola/go/pkg/mod/github.com/childe/healer@v0.6.11/fetch_response.go:365 +0x12b
github.com/childe/healer.(*fetchResponseStreamDecoder).decodeResponses(0xc010df3e00, 0x0)
#011/home/zcola/go/pkg/mod/github.com/childe/healer@v0.6.11/fetch_response.go:398 +0xed
github.com/childe/healer.(*fetchResponseStreamDecoder).streamDecode(0xc010df3e00, {0x1287d18, 0xc010d96500}, 0x0?)
#011/home/zcola/go/pkg/mod/github.com/childe/healer@v0.6.11/fetch_response.go:445 +0xa5
github.com/childe/healer.(*SimpleConsumer).consumeLoop.func1()
#011/home/zcola/go/pkg/mod/github.com/childe/healer@v0.6.11/simple_consumer.go:436 +0x37
created by github.com/childe/healer.(*SimpleConsumer).consumeLoop in goroutine 1858
#011/home/zcola/go/pkg/mod/github.com/childe/healer@v0.6.11/simple_consumer.go:435 +0x85f

```

**Comment by childe** [comment]
感谢反馈，你的kafka版本是什么？

容易复现不？如果容易，希望能抓个包发我看看。

**Comment by zcola** [comment]
[kafka_packets.pcap.tar.gz](https://github.com/user-attachments/files/17373024/kafka_packets.pcap.tar.gz)

**Comment by zcola** [comment]
后面给我的版本，昨天试了是无法消费的一直报错，今天想重现抓包，但是目前还是没出现，下面报错昨天也出现了，看起来是也需要解决的
```
E1016 14:34:59.815639       1 brokers.go:240] "get metadata failed" err="read response of 3(1) from canal-kafka07-erie.i.nease.net:9092 error: EOF" logger="healer" topics=["erie_dasdogtail"] brokerAddress="cxt:9092"
E1016 14:35:02.012544       1 simple_consumer.go:469] "message error" err="max.bytes parameter is too small. This size must be at least as large as the maximum message size the server allows or else it is possible for the producer to send messages larger than the consumer can fetch. If that happens, the consumer can get stuck trying to fetch a large message on a certain partition." logger="healer" topic="wellandsail" partitionID=1
I1016 14:35:02.012585       1 simple_consumer.go:474] "fetch.max.bytes is too small, double it" logger="healer" new FetchMaxBytes=20971520

```

**Comment by lucky0137** [comment]
我用3.7版本的Kafka也发现有这个问题

**Comment by childe** [comment]
@zcola healer v0.6.16 更新了针对 kafka 1.1.1 的比较新协议。

**Comment by childe** [comment]
@lucky0137 是指哪个问题？ decode 的时候 panic ? 发我具体的panic 堆栈看下吧。

**Comment by childe** [comment]
https://github.com/childe/gohangout/commit/e3e5ebab3c44bdaccf4901b4ef4a310fdf781c16 处理了这个问题，有问题再开吧。

**Comment by zcola** [comment]
看起来解决了
