### ISSUE TITLE
gohangout消费异常问题

### ISSUE THREAD

**Issue by yasincyx** [childe/gohangout#261]
gohangout版本：v1.10.12
kafka版本：1.1.1

kafka数据开了snappy压缩，在消费的过程中会出现消费失败导致中断退出

```
I1127 17:15:26.150972       1 bulk_http.go:170] bulk done with execution_id 23 3.250 24588 7565.538
E1127 17:15:26.479384       1 simple_consumer.go:469] "message error" err="uncompress records bytes error: uncompress snappy records error: malformed xerial framing" logger="healer" topic="tang_h72_istio_accesslog" partitionID=1
E1127 17:15:27.639333       1 simple_consumer.go:469] "message error" err="uncompress records bytes error: uncompress snappy records error: malformed xerial framing" logger="healer" topic="tang_h72_istio_accesslog" partitionID=1
E1127 17:15:29.238325       1 simple_consumer.go:469] "message error" err="uncompress records bytes error: uncompress snappy records error: malformed xerial framing" logger="healer" topic="tang_h72_istio_accesslog" partitionID=1
E1127 17:15:30.360828       1 simple_consumer.go:469] "message error" err="uncompress records bytes error: uncompress snappy records error: malformed xerial framing" logger="healer" topic="tang_h72_istio_accesslog" partitionID=1
```

用gohangout版本v1.10.10 ，则会出现一下异常

```
panic: runtime error: makeslice: len out of range
goroutine 472 [running]:
github.com/childe/healer.decodeHeader({0xc094ca60ea, 0x320de, 0x35f16})
#011/home/zcola/go/pkg/mod/github.com/childe/healer@v0.6.11/message.go:36 +0x118
github.com/childe/healer.DecodeToRecord({0xc094ca6082, 0x32146, 0x35f7e})
#011/home/zcola/go/pkg/mod/github.com/childe/healer@v0.6.11/message.go:96 +0x545
github.com/childe/healer.(*fetchResponseStreamDecoder).decodeRecordsMagic2(0xc0004b1440, {0xc09262dd40, 0x18}, 0x4, {0xc092cd41c8, 0x11, 0x11?})
#011/home/zcola/go/pkg/mod/github.com/childe/healer@v0.6.11/fetch_response.go:236 +0x4fd
github.com/childe/healer.(*fetchResponseStreamDecoder).decodeMessageSet(0xc0004b1440, {0xc09262dd40, 0x18}, 0x4, 0x9d8df0, 0x2dd8?)
#011/home/zcola/go/pkg/mod/github.com/childe/healer@v0.6.11/fetch_response.go:305 +0x171
github.com/childe/healer.(*fetchResponseStreamDecoder).decodePartitionResponse(0xc0004b1440, {0xc09262dd40, 0x18}, 0x0)
#011/home/zcola/go/pkg/mod/github.com/childe/healer@v0.6.11/fetch_response.go:365 +0x12b
github.com/childe/healer.(*fetchResponseStreamDecoder).decodeResponses(0xc0004b1440, 0x0)
#011/home/zcola/go/pkg/mod/github.com/childe/healer@v0.6.11/fetch_response.go:398 +0xed
github.com/childe/healer.(*fetchResponseStreamDecoder).streamDecode(0xc0004b1440, {0x128ddf0, 0xc0926399a0}, 0x17dfcc0?)
#011/home/zcola/go/pkg/mod/github.com/childe/healer@v0.6.11/fetch_response.go:445 +0xa5
github.com/childe/healer.(*SimpleConsumer).consumeLoop.func1()
#011/home/zcola/go/pkg/mod/github.com/childe/healer@v0.6.11/simple_consumer.go:436 +0x37
created by github.com/childe/healer.(*SimpleConsumer).consumeLoop in goroutine 236
#011/home/zcola/go/pkg/mod/github.com/childe/healer@v0.6.11/simple_consumer.go:435 +0x85f
```

更换为gohangout : v1.8.2 旧版，消费正常

**Comment by childe** [comment]
我这边使用 v1.10.12和v1.10.10，kafka使用 1.1.1，消费Snappy压缩的数据，一直未能复现这个报错。我再继续看看snappy相关的一些资料吧。

**Comment by childe** [comment]
能否看一下
1. Producer Client 的版本
2. Topic本身配置了Snappy压缩，还是 Producer 配置的？

**Comment by yasincyx** [comment]
是broker端配置的snappy压缩

**Comment by zcola** [comment]
@childe 这个问题我们先用https://github.com/arterhuo/gohangout-input-confluent-kafka-go 替换消费了，不过最好希望能原来的也支持哈，不然升级上去还得更新配置文件的input 为新插件
