### ISSUE TITLE
kafka集群中某broker宕机后gohangout panic

### ISSUE THREAD

**Issue by zhoufwind** [childe/gohangout#41]
线上kafka集群中某broker（ip地址是：10.10.52.153）意外宕机，gohangout panic，消费端中断消费，异常日志如下：

```
E0701 13:04:11.135321       1 broker.go:272] write only partial data. api: 1 CorrelationID: 108513404
E0701 13:04:11.135331       1 simple_consumer.go:326] fetch error:read tcp4 10.63.142.198:40734->10.10.52.153:9092: use of closed network connection
E0701 13:04:11.135345       1 fetch_response.go:226] could read enough bytes(4) to get fetchresponse length. read 0 bytes
I0701 13:04:11.135233       1 broker.go:174] broker 10.10.52.153:9092 dead, reopen it
E0701 13:04:11.135348       1 broker.go:177] could not conn to 10.10.52.153:9092: dial tcp4 10.10.52.153:9092: connect: connection refused
E0701 13:04:11.135365       1 broker.go:269] write tcp 10.63.142.198:32776->10.10.52.153:9092: use of closed network connection
I0701 13:04:11.135371       1 broker.go:174] broker 10.10.52.153:9092 dead, reopen it
E0701 13:04:11.135384       1 broker.go:272] write only partial data. api: 1 CorrelationID: 107643126
E0701 13:04:11.135399       1 simple_consumer.go:326] fetch error:read tcp 10.63.142.198:32776->10.10.52.153:9092: use of closed network connection
E0701 13:04:11.135412       1 fetch_response.go:226] could read enough bytes(4) to get fetchresponse length. read 0 bytes
I0701 13:04:11.135431       1 broker.go:174] broker 10.10.52.153:9092 dead, reopen it
E0701 13:04:11.135458       1 broker.go:177] could not conn to 10.10.52.153:9092: dial tcp4 10.10.52.153:9092: connect: connection refused
E0701 13:04:11.135476       1 broker.go:269] write tcp 10.63.142.198:32772->10.10.52.153:9092: use of closed network connection
E0701 13:04:11.135495       1 broker.go:272] write only partial data. api: 1 CorrelationID: 108919885
E0701 13:04:11.135507       1 simple_consumer.go:326] fetch error:read tcp 10.63.142.198:32772->10.10.52.153:9092: use of closed network connection
E0701 13:04:11.135520       1 fetch_response.go:226] could read enough bytes(4) to get fetchresponse length. read 0 bytes
E0701 13:04:11.135493       1 broker.go:177] could not conn to 10.10.52.153:9092: dial tcp4 10.10.52.153:9092: connect: connection refused
E0701 13:04:11.135541       1 broker.go:269] write tcp 10.63.142.198:32782->10.10.52.153:9092: use of closed network connection
E0701 13:04:11.135560       1 broker.go:272] write only partial data. api: 1 CorrelationID: 107964938
E0701 13:04:11.135569       1 broker.go:177] could not conn to 10.10.52.153:9092: dial tcp4 10.10.52.153:9092: connect: connection refused
E0701 13:04:11.135583       1 fetch_response.go:226] could read enough bytes(4) to get fetchresponse length. read 0 bytes
E0701 13:04:11.135591       1 broker.go:269] write tcp4 10.63.142.198:36866->10.10.52.153:9092: use of closed network connection
I0701 13:04:11.135603       1 broker.go:174] broker 10.10.52.153:9092 dead, reopen it
E0701 13:04:11.135610       1 broker.go:272] write only partial data. api: 1 CorrelationID: 108123359
E0701 13:04:11.135626       1 simple_consumer.go:326] fetch error:read tcp4 10.63.142.198:36866->10.10.52.153:9092: use of closed network connection
E0701 13:04:11.135573       1 simple_consumer.go:326] fetch error:read tcp 10.63.142.198:32782->10.10.52.153:9092: use of closed network connection
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x7e6e66]
 goroutine 38 [running]:
github.com/childe/gohangout/vendor/github.com/childe/healer.(*GroupConsumer).Consume.func2(0xc0000dc6c0)
	/home/soft/go/src/github.com/childe/gohangout/vendor/github.com/childe/healer/group_consumer.go:429 +0x1d6
created by github.com/childe/gohangout/vendor/github.com/childe/healer.(*GroupConsumer).Consume
	/home/soft/go/src/github.com/childe/gohangout/vendor/github.com/childe/healer/group_consumer.go:410 +0xcb
```

gohangout配置如下，其中`kafka3.ops.yeshj.com`dns解析是`10.10.52.153`：
```
    inputs:
        #- Stdin:
        #    codec: json
        - Kafka:
            topic:
                log4j_v1: 1
            #assign:
            #    healer.test: [0]
            codec: json
            consumer_settings:
                bootstrap.servers: "kafka1.ops.yeshj.com:9092,kafka2.ops.yeshj.com:9092,kafka3.ops.yeshj.com:9092"
                group.id: gohangout-log4j_v1-k8s-prod-topic-online
                max.partition.fetch.bytes: 10485760
                auto.commit.interval.ms: 5000
                from.beginning: false
```

后来重启异常broker后恢复。正常情况下宕掉一个broker应该不至于导致整个进程挂掉，晚点我再做下测试，看能否重现，先开个issue跟踪下这个问题。

**Comment by childe** [comment]
是哪一个版本?

**Comment by zhoufwind** [comment]
gohangout更新至最新版本，同时扩容kafka副本数量，今早模拟broker宕机场景，未能重现gohangout panic现象，关闭这个问题，感谢 @childe 协助问题排查。
